In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
df=pd.read_csv("onlinefraud.csv.zip")

In [3]:
df.shape

(6362620, 11)

In [4]:
df.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [5]:
df.tail()

step      type      amount     nameOrig  oldbalanceOrg  \
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
6362615             0.0   C776919290            0.00       339682.13        1   
6362616             0.0  C1881841831            0.00            0.00        1   
6362617             0.0  C1365125890        68488.84      6379898.11        1   
6362618             0.0  C2080388513            0.00            0.00        1   
6362619             0.0   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0

In [6]:
df.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [8]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()
le

LabelEncoder()

In [11]:
df['type'] = le.fit_transform(df['type'])

In [12]:
df

step  type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0           1     3     9839.64  C1231006815      170136.00       160296.36   
1           1     3     1864.28  C1666544295       21249.00        19384.72   
2           1     4      181.00  C1305486145         181.00            0.00   
3           1     1      181.00   C840083671         181.00            0.00   
4           1     3    11668.14  C2048537720       41554.00        29885.86   
...       ...   ...         ...          ...            ...             ...   
6362615   743     1   339682.13   C786484425      339682.13            0.00   
6362616   743     4  6311409.28  C1529008245     6311409.28            0.00   
6362617   743     1  6311409.28  C1162922333     6311409.28            0.00   
6362618   743     4   850002.52  C1685995037      850002.52            0.00   
6362619   743     1   850002.52  C1280323807      850002.52            0.00   

            nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0        M1979787155            0.00            0.00        0               0  
1        M2044282225            0.00            0.00        0               0  
2         C553264065            0.00            0.00        1               0  
3          C38997010        21182.00            0.00        1               0  
4        M1230701703            0.00            0.00        0               0  
...              ...             ...             ...      ...             ...  
6362615   C776919290            0.00       339682.13        1               0  
6362616  C1881841831            0.00            0.00        1               0  
6362617  C1365125890        68488.84      6379898.11        1               0  
6362618  C2080388513            0.00            0.00        1               0  
6362619   C873221189      6510099.11      7360101.63        1               0  

[6362620 rows x 11 columns]

In [13]:
df['nameOrig'] =df['nameOrig'].apply(lambda x: int(''.join(re.findall(r'\d+',str(x)))))


In [14]:
df

step  type      amount    nameOrig  oldbalanceOrg  newbalanceOrig  \
0           1     3     9839.64  1231006815      170136.00       160296.36   
1           1     3     1864.28  1666544295       21249.00        19384.72   
2           1     4      181.00  1305486145         181.00            0.00   
3           1     1      181.00   840083671         181.00            0.00   
4           1     3    11668.14  2048537720       41554.00        29885.86   
...       ...   ...         ...         ...            ...             ...   
6362615   743     1   339682.13   786484425      339682.13            0.00   
6362616   743     4  6311409.28  1529008245     6311409.28            0.00   
6362617   743     1  6311409.28  1162922333     6311409.28            0.00   
6362618   743     4   850002.52  1685995037      850002.52            0.00   
6362619   743     1   850002.52  1280323807      850002.52            0.00   

            nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0        M1979787155            0.00            0.00        0               0  
1        M2044282225            0.00            0.00        0               0  
2         C553264065            0.00            0.00        1               0  
3          C38997010        21182.00            0.00        1               0  
4        M1230701703            0.00            0.00        0               0  
...              ...             ...             ...      ...             ...  
6362615   C776919290            0.00       339682.13        1               0  
6362616  C1881841831            0.00            0.00        1               0  
6362617  C1365125890        68488.84      6379898.11        1               0  
6362618  C2080388513            0.00            0.00        1               0  
6362619   C873221189      6510099.11      7360101.63        1               0  

[6362620 rows x 11 columns]

In [15]:
df['nameDest'] =df['nameDest'].apply(lambda x: int(''.join(re.findall(r'\d+',str(x)))))

In [16]:
df

step  type      amount    nameOrig  oldbalanceOrg  newbalanceOrig  \
0           1     3     9839.64  1231006815      170136.00       160296.36   
1           1     3     1864.28  1666544295       21249.00        19384.72   
2           1     4      181.00  1305486145         181.00            0.00   
3           1     1      181.00   840083671         181.00            0.00   
4           1     3    11668.14  2048537720       41554.00        29885.86   
...       ...   ...         ...         ...            ...             ...   
6362615   743     1   339682.13   786484425      339682.13            0.00   
6362616   743     4  6311409.28  1529008245     6311409.28            0.00   
6362617   743     1  6311409.28  1162922333     6311409.28            0.00   
6362618   743     4   850002.52  1685995037      850002.52            0.00   
6362619   743     1   850002.52  1280323807      850002.52            0.00   

           nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0        1979787155            0.00            0.00        0               0  
1        2044282225            0.00            0.00        0               0  
2         553264065            0.00            0.00        1               0  
3          38997010        21182.00            0.00        1               0  
4        1230701703            0.00            0.00        0               0  
...             ...             ...             ...      ...             ...  
6362615   776919290            0.00       339682.13        1               0  
6362616  1881841831            0.00            0.00        1               0  
6362617  1365125890        68488.84      6379898.11        1               0  
6362618  2080388513            0.00            0.00        1               0  
6362619   873221189      6510099.11      7360101.63        1               0  

[6362620 rows x 11 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            int32  
 2   amount          float64
 3   nameOrig        int64  
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        int64  
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int32(1), int64(5)
memory usage: 509.7 MB


In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [20]:
x=df.drop(columns=['isFraud'])
x.head()

step  type    amount    nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1     3   9839.64  1231006815       170136.0       160296.36   
1     1     3   1864.28  1666544295        21249.0        19384.72   
2     1     4    181.00  1305486145          181.0            0.00   
3     1     1    181.00   840083671          181.0            0.00   
4     1     3  11668.14  2048537720        41554.0        29885.86   

     nameDest  oldbalanceDest  newbalanceDest  isFlaggedFraud  
0  1979787155             0.0             0.0               0  
1  2044282225             0.0             0.0               0  
2   553264065             0.0             0.0               0  
3    38997010         21182.0             0.0               0  
4  1230701703             0.0             0.0               0

In [21]:
y=df[['isFraud']]
y.head()

isFraud
0        0
1        0
2        1
3        1
4        0

In [22]:
from sklearn.model_selection import train_test_split


In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [24]:
print("x_train shape",x_train.shape)
print("x_test shape",x_test.shape)
print("y_train shape",y_train.shape)
print("y_test shape",y_test.shape)

x_train shape (5090096, 10)
x_test shape (1272524, 10)
y_train shape (5090096, 1)
y_test shape (1272524, 1)


In [25]:
x_train_scaler = scaler.fit_transform(x_train)
x_train_scaler

array([[ 2.63914941e+00, -1.26962110e+00,  3.43452920e-01, ...,
        -1.74992029e-01, -3.01147109e-01, -1.59811948e-03],
       [-5.57841379e-01, -1.26962110e+00,  5.43553255e-02, ...,
        -8.65455022e-02, -1.71883432e-01, -1.59811948e-03],
       [ 9.73903657e-01,  9.52489549e-01, -2.65600525e-01, ...,
        -3.24180770e-01, -3.33781517e-01, -1.59811948e-03],
       ...,
       [ 7.49060349e-01, -5.28917553e-01, -2.81205844e-01, ...,
        -2.29026717e-01, -2.42865199e-01, -1.59811948e-03],
       [ 4.46927154e-01, -5.28917553e-01, -1.77416386e-01, ...,
        -2.48676791e-01, -2.44013393e-01, -1.59811948e-03],
       [-5.92973145e-01, -5.28917553e-01, -1.49694324e-01, ...,
        -3.24180770e-01, -3.09316249e-01, -1.59811948e-03]])

In [26]:
x_test_scaler = scaler.fit_transform(x_test)
x_test_scaler

array([[ 2.42913628e-01, -1.26967162e+00,  2.44704413e-01, ...,
        -1.90402699e-01, -2.98978378e-01, -1.53542338e-03],
       [-1.60432798e+00,  9.52038530e-01, -2.75210822e-01, ...,
        -3.22376778e-01, -3.31961352e-01, -1.53542338e-03],
       [-1.63944664e+00, -1.26967162e+00, -4.57206607e-02, ...,
        -2.63655226e-01, -3.18725425e-01, -1.53542338e-03],
       ...,
       [ 9.52310595e-01, -5.29101569e-01,  1.11357251e-01, ...,
        -3.15431831e-01, -2.58460321e-01, -1.53542338e-03],
       [-1.41468721e+00, -5.29101569e-01,  3.21992856e-02, ...,
        -1.50277177e-01, -1.18739423e-01, -1.53542338e-03],
       [-6.13981719e-01, -1.26967162e+00, -2.15773550e-01, ...,
        -1.48878027e-01, -1.84402113e-01, -1.53542338e-03]])

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
LR=LogisticRegression()
LR

LogisticRegression()

In [29]:
LR.fit(x_train_scaler,y_train)

C:\Users\syed.manisha\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [30]:
y_pred = LR.predict(x_test_scaler)

In [31]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [32]:
from sklearn.metrics import classification_report,accuracy_score

In [33]:
score=accuracy_score(y_pred,y_test)

In [34]:
score

0.9992094451656708

In [35]:
score1=classification_report(y_pred,y_test)

In [36]:
score1

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00   1271772\n           1       0.42      0.91      0.58       752\n\n    accuracy                           1.00   1272524\n   macro avg       0.71      0.95      0.79   1272524\nweighted avg       1.00      1.00      1.00   1272524\n'

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
DT=DecisionTreeClassifier()

In [40]:
DT.fit(x_train_scaler,y_train)

DecisionTreeClassifier()

In [41]:
y_pred_DT=DT.predict(x_test_scaler)

In [42]:
y_pred_DT

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
DT_score=accuracy_score(y_pred_DT,y_test)

In [44]:
DT_score

0.9992345920391286

In [45]:
DT_score=classification_report(y_pred_DT,y_test)

In [46]:
DT_score

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00   1271542\n           1       0.50      0.83      0.63       982\n\n    accuracy                           1.00   1272524\n   macro avg       0.75      0.91      0.81   1272524\nweighted avg       1.00      1.00      1.00   1272524\n'

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
RF=RandomForestClassifier()

In [ ]:
RF.fit(x_train_scaler,y_train)

In [ ]:
y_pred_RF=RF.predict(x_test_scaler)

In [ ]:
y_pred_RF

In [ ]:
RF_score=accuracy_score(y_pred_RF,y_test)

In [ ]:
RF_score=classification_report(y_pred_RF,y_test)